### ISSUE TITLE
Deposits are not appearing in history

### ISSUE THREAD

**Issue by StDogbert** [rubykube/microkube#106]
Configured everything. Got deposit address. All daemons are running. Sent some eth to address. Deposits are not there. Not in balance, not in deposits history. Which container logs should I check to find the issue?

**Comment by etfx-dev** [comment]
Figured it out. I was using custom geth derived coin with name which was not equal eth. While also using Geth gateway. Checked blockchain logs. In sources for blockchain daemon in peatio got to BlockchainService and WalletService and there were hardcoded validation for currency name for eth, to distinguish from erc20 tokens. Changed those validation for is_erc20 and created my own peatio image for docker. Problem fixed.

**Comment by StDogbert** [comment]
Figured it out. I was using custom geth derived coin with name which was not equal eth. While also using Geth gateway. Checked blockchain logs. In sources for blockchain daemon in peatio got to BlockchainService and WalletService and there were hardcoded validation for currency name for eth, to distinguish from erc20 tokens. Changed those validation for is_erc20 and created my own peatio image for docker. Problem fixed.

**Comment by TTcoinDeveloper** [comment]
@StDogbert  I have not gotten further than 404 error how did you tweak it? can u help me?

**Comment by StDogbert** [comment]
@TTcoinDeveloper Sure. What do you mean by 404? Where? What is your request? You can't get to the specific page or can't launch anything at all?

**Comment by pblab-dev** [comment]
It's hard to find information, I suggest you see this https://bitcointalk.org/index.php?topic=5202005.new#new
