### ISSUE TITLE
Ability to configure cryptonodes

### ISSUE THREAD

**Issue by shal** [rubykube/microkube#29]
Now all currencies are enabled, but we don't have crypto-nodes for them.

I suggest:

- [ ] Add geth and bitcoind to `cryptonodes.yaml`. 

- [ ] Add ability to enable geth and bitcoind in `app.yaml`.

- [ ] Update seed files for peatio from default one.

**Comment by champmine** [comment]
Hi Shal,

thank you. But as always, you are so minimalistic in what you say. Can you please be more specific and add some details?

Thanks!

**Comment by champmine** [comment]
really, closing this almost a year later?
