### ISSUE TITLE
Switch from envs to templates in compose files

### ISSUE THREAD

**Issue by shal** [rubykube/microkube#30]
- [x] Remove envs form docker compose files.
- [x] Add configurations to `app.yaml` and use power of ruby as much as possible.

Suggestions:

- Make a loop and generate code for each peatio daemon, instead of copy paste.

**Comment by mod** [comment]
- [ ] Update all seeds to use only ETH + 2 tokens + 1 FIAT
- [ ] Clean peatio.env barong.env config files
- [ ] Check daemons and geth for address generation
- [ ] Move template renderer to lib
