### ISSUE TITLE
NameError: uninitialized constant Pathname

### ISSUE THREAD

**Issue by dragon28** [rubykube/microkube#7]
issue:

```
~/microkube$ rake render:config
rake aborted!
NameError: uninitialized constant Pathname
lib/tasks/render.rake:3:in `<top (required)>'
/home/dragon/microkube/Rakefile:9:in `load'
/home/dragon/microkube/Rakefile:9:in `block in <top (required)>'
/home/dragon/microkube/Rakefile:8:in `each'
/home/dragon/microkube/Rakefile:8:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by dragon28** [comment]
@pkucherenk0 

Thank you for the information. 

Manage to perform bundle install and bundle exec rake render:config

However, when it come to bundle exec rake service:all[start]

~/microkube$ bundle exec rake service:all[start]
----- Starting the proxy -----
docker-compose up -d proxy
ERROR: Version in "./compose/app.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
rake aborted!
Command failed with status (1): [docker-compose up -d proxy...]
lib/tasks/service.rake:25:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:33:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:185:in `start'
lib/tasks/service.rake:7:in `call'
lib/tasks/service.rake:7:in `block (2 levels) in <top (required)>'
lib/tasks/service.rake:202:in `block (2 levels) in <top (required)>'
/home/dragon/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/home/dragon/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
Tasks: TOP => service:proxy
(See full trace by running task with --trace)

docker-compose version:

```
~/microkube$ docker-compose version
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

```

Thanks

**Comment by pkucherenk0** [comment]
I suggest you update your docker-compose version.

The "./compose/app.yaml" contains the line: "version: '3.6'" and if you will visit https://docs.docker.com/compose/compose-file/ you will see that 3.6 required docker-compose version 18.02.0+.

**Comment by dragon28** [comment]
> I suggest you update your docker version.
> 
> The "./compose/app.yaml" contains the line: "version: '3.6'" and if you will visit https://docs.docker.com/compose/compose-file/ you will see that 3.6 required docker version 18.02.0+.
> 
> My versions:
> Docker version 18.09.0, build 4d60db4
> docker-compose version 1.23.1, build b02f1306

@pkucherenk0 

My docker version information:

```
~/workbench$ docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by dragon28** [comment]
@pkucherenk0 

Manage to fix it by upgrading the removing the old docker-compose and upgrade it to the latest version from the docker website.

Thank and I apologies for any inconvenient.
