### ISSUE TITLE
frontend router errors

### ISSUE THREAD

**Issue by hashfaster** [rubykube/microkube#8]
the provider comes up (in monitor.) but when I try to get to www/peatio, results in 404.

when I try tower., error, Bad Gateway.

No errors were present when starting components. Any ideas?

**Comment by Thedabest** [comment]
me too

**Comment by hashfaster** [comment]
Last pull seemed to improve things, but now the issue is the seeds for barong do not seem to work. As the login page does nothing when I press "Sign in"

**Comment by dudetheman** [comment]
all pages are 404 for me as well

**Comment by mod** [comment]
@hashfaster updated you can try again
