### ISSUE TITLE
deposit_coin_address error

### ISSUE THREAD

**Issue by fedevmoya** [rubykube/microkube#9]
The deposit_coin_address daemon logs the following error

`#<ActiveRecord::StatementInvalid: Mysql2::Error: Table 'peatio_development.authentications' doesn't exist: SHOW FULL FIELDS FROM `authentications`>`

Changing the image from rubykube/peatio:1.9.1-rc.20 to rubykube/peatio:2.0.0.alpha in file compose/daemons.yaml fixes the error and the daemon works fine.

**Comment by mod** [comment]
thank you this issue has been resolved
