### ISSUE TITLE
How to connect websocket?

### ISSUE THREAD

**Issue by Thedabest** [rubykube/microkube#91]
rake service:all[start]
rake service:daemons[start]
ws://ws.ranger.app.local not working
on monitor cant finds ranger,... http://monitor.app.local/dashboard/
![image](https://user-images.githubusercontent.com/40519768/52487031-45d0ca00-2bef-11e9-9a08-bbe13d7aa08c.png)
TKS FOR YOUR HELP

**Comment by endofthepain** [comment]
fixed ?

**Comment by TTcoinDeveloper** [comment]
fixed?
