### ISSUE TITLE
No Trading Page ? 

### ISSUE THREAD

**Issue by hasanaliqureshi** [rubykube/microkube#92]
![image](https://user-images.githubusercontent.com/12941929/52539695-14006480-2da3-11e9-959b-c0ff0c19c146.png)

Trading page is coming soon. Is microkube an incomplete project ?

**Comment by Thedabest** [comment]
no

**Comment by atbmatt** [comment]
Microkube uses Peatio 2.0.xx. There is no trade UI provided for this version, only what you see in mikroapp is provided. If you want a ready made trade UI, try installing Peatio 1.9 with the workbench project.

**Comment by huuhait** [comment]
can u close issue?
