### ISSUE TITLE
Can not login after `rake service:all`

### ISSUE THREAD

**Issue by mengzyou** [rubykube/microkube#98]
## Issue Description

Follow the READEM, deploy the all services via `rake service:all`, but can not login on `www.<domain>` with the default seeds user/password, it reports error message **Oups! Error occurs, please try again later.** 

![image](https://user-images.githubusercontent.com/360603/52924800-3aa53900-3369-11e9-9357-fa94ecb9a3a0.png)

## Version

0.1.19

**Comment by lsethi** [comment]
Check Browser console logs. May be you have not setup ssl correctly

**Comment by mengzyou** [comment]
@lsethi Yes, you are correct, it reports:  

```
xhr.js:173 Mixed Content: The page at 'https://www.<domain>/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.<domain>/api/v2/barong/identity/sessions'. This request has been blocked; the content must be served over HTTPS.
```

But, how can I setup ssl correctly?

**Comment by lsethi-xoriant** [comment]
@mengzyou  You need to edit  following config files and https instead of http.
microkube/config/frontend/env.js
microkube/config/frontend/tower.js
 `window.env = {
  API_URL: 'https://www.<domain>
};`

**Comment by mengzyou** [comment]
@lsethi-xoriant Thank you! I tried to edit those 2 files, but after I executed `rake service:all[start]` it will re-render those 2 files, so finally I changed files under `microkube/templates/config/frontend/`, it works.

**Comment by TTcoinDeveloper** [comment]
hello I have this problem to but i notice ( 'https://www.<domain> }; ) and i have some problems with editing /etc/hosts because  www.domain.local confuses me ( .local ) part, can u help me? my domain is www.myttcoin.com I am not sure what to put in the /etc/hosts or here
